name: Chat
version: '${project.version}'
main: guevin1.chat.main
api-version: 1.17
authors: [ Guevin1 ]
softdepend: [ PlaceholderAPI ]
description: Chat For bloxen
commands:
  w:
    description: w
    permission: chat.w
    aliases:
      - msg
      - tell
    usage: /w <player> <Message>
  spy:
    description: spy
    permission: chat.spy
    usage: /spy
  me:
    description: me
    permission: chat.me
    usage: /me <message>